include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.json"
    - "**/*.yaml"
    - "*.yaml"
    - "**/*.md"
    - "**/*.txt"
    - "**/*.g.dart"
    - "/*.g.dart"
    - "*.g.dart"
    - "**/*_model.dart"
linter:
  rules:
