name: shartflix_case
description: "Shartflix case study"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Routing
  go_router: ^16.0.0

  # Core
  equatable: ^2.0.7
  get_it: ^8.0.3

  # State Management
  flutter_bloc: ^9.1.1

  # Storage 
  shared_preferences: ^2.5.3

  # Token Security
  flutter_secure_storage: ^9.2.4

  # Config
  easy_localization: ^3.0.7+1

  # Ui
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1

  # Network
  dio: ^5.8.0+1

  # Image Picker
  image_picker: ^1.1.2

  # Native Splash
  flutter_native_splash: ^2.4.6

  # Icons
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.15
  go_router_builder: ^3.0.1
  very_good_analysis: ^9.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

flutter_native_splash:
  color: "#000000"
  image: "assets/images/img_logo.png"
  android: true
  ios: true
  web: false
  fullscreen: true
  android_12:
    color: "#090909"
    image: "assets/images/img_logo.png"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_logo.png"
  min_sdk_android: 21