name: shartflix_case
description: "Shartflix case study"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Routing
  go_router: ^16.0.0

  # Core
  equatable: ^2.0.7
  get_it: ^8.0.3

  # State Management
  flutter_bloc: ^9.1.1

  # Storage 
  shared_preferences: ^2.5.3

  # Token Security
  flutter_secure_storage: ^9.2.4

  # Config
  easy_localization: ^3.0.7+1

  # Ui
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1

  # Network
  dio: ^5.8.0+1

  # Image Picker
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  go_router_builder: ^3.0.1
  very_good_analysis: ^9.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/