import 'package:flutter/material.dart';

/// Project custom colors
final class CustomColorScheme {
  CustomColorScheme._();

  /// Light color scheme set
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff1971c2),
      surfaceTint: Color(0xff1971c2),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffd0e4f7),
      onPrimaryContainer: Color(0xff001d33),
      secondary: Color(0xff5a6473),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffdae2f1),
      onSecondaryContainer: Color(0xff1c2733),
      tertiary: Color(0xff6d4e7d),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xfff2d9f7),
      onTertiaryContainer: Color(0xff2b1733),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfff8faff),
      onSurface: Color(0xff191c1f),
      onSurfaceVariant: Color(0xff44474e),
      outline: Color(0xff73777e),
      outlineVariant: Color(0xffc4c6cf),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff303336),
      inversePrimary: Color(0xff62b1f9),
      primaryFixed: Color(0xffd0e4f7),
      onPrimaryFixed: Color(0xff001d33),
      primaryFixedDim: Color(0xff9fcaf0),
      onPrimaryFixedVariant: Color(0xff004580),
      secondaryFixed: Color(0xffdae2f1),
      onSecondaryFixed: Color(0xff1c2733),
      secondaryFixedDim: Color(0xffbcc8d9),
      onSecondaryFixedVariant: Color(0xff404b5a),
      tertiaryFixed: Color(0xfff2d9f7),
      onTertiaryFixed: Color(0xff2b1733),
      tertiaryFixedDim: Color(0xffd1aed8),
      onTertiaryFixedVariant: Color(0xff50345a),
      surfaceDim: Color(0xffe0e3ea),
      surfaceBright: Color(0xffffffff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff3f6fa),
      surfaceContainer: Color(0xffebeff4),
      surfaceContainerHigh: Color(0xffe3e8ee),
      surfaceContainerHighest: Color(0xffdce2e9),
    );
  }

  /// Dark color scheme set
  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xff1971c2),
      surfaceTint: Color(0xff62b1f9),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff004580),
      onPrimaryContainer: Color(0xffd0e4f7),
      secondary: Color(0xffbcc8d9),
      onSecondary: Color(0xff2a3442),
      secondaryContainer: Color(0xff404b5a),
      onSecondaryContainer: Color(0xffdae2f1),
      tertiary: Color(0xffd1aed8),
      onTertiary: Color(0xff422b4d),
      tertiaryContainer: Color(0xff50345a),
      onTertiaryContainer: Color(0xfff2d9f7),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff121417),
      onSurface: Color(0xffe3e4e8),
      onSurfaceVariant: Color(0xffc4c6cf),
      outline: Color(0xff888b94),
      outlineVariant: Color(0xff44474e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe3e4e8),
      inversePrimary: Color(0xff1971c2),
      primaryFixed: Color(0xffd0e4f7),
      onPrimaryFixed: Color(0xff001d33),
      primaryFixedDim: Color(0xff9fcaf0),
      onPrimaryFixedVariant: Color(0xff004580),
      secondaryFixed: Color(0xffdae2f1),
      onSecondaryFixed: Color(0xff1c2733),
      secondaryFixedDim: Color(0xffbcc8d9),
      onSecondaryFixedVariant: Color(0xff404b5a),
      tertiaryFixed: Color(0xfff2d9f7),
      onTertiaryFixed: Color(0xff2b1733),
      tertiaryFixedDim: Color(0xffd1aed8),
      onTertiaryFixedVariant: Color(0xff50345a),
      surfaceDim: Color(0xff191b1f),
      surfaceBright: Color(0xff383a3e),
      surfaceContainerLowest: Color(0xff0d0f12),
      surfaceContainerLow: Color(0xff17191c),
      surfaceContainer: Color(0xff1d1f22),
      surfaceContainerHigh: Color(0xff26292c),
      surfaceContainerHighest: Color(0xff303336),
    );
  }
}
